version: '3.8'

services:
  # MongoDB数据库服务
  mongodb:
    image: mongo:8.0
    container_name: tts-flow-mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: tts_flow_password_2024
      MONGO_INITDB_DATABASE: tts_flow
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - tts-flow-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 后端API服务（开发模式）
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: tts-flow-backend-dev
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://admin:tts_flow_password_2024@mongodb:27017
      - DATABASE_NAME=tts_flow
      - SECRET_KEY=tts_flow_secret_key_2024_dev
      - DEBUG=True
      - ENVIRONMENT=development
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - tts-flow-network
    volumes:
      - ../backend:/app
      - backend_logs:/app/logs
      - backend_uploads:/app/uploads
      - backend_static_tts:/app/static/tts_wav
      - ./.env:/app/.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # 前端开发服务
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
    container_name: tts-flow-frontend-dev
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - tts-flow-network
    volumes:
      - ../frontend:/app
      - /app/node_modules
    command: pnpm dev



volumes:
  mongodb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/mongodb
  backend_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/backend/logs
  backend_uploads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/backend/uploads
  backend_static_tts:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/backend/static/tts_wav


networks:
  tts-flow-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 