version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: tts-flow-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    networks:
      - tts-flow-network

  backend:
    build: .
    container_name: tts-flow-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://admin:password@mongodb:27017
      - DATABASE_NAME=tts_flow
      - SECRET_KEY=your-secret-key-here-change-in-production
      - DEBUG=True
    depends_on:
      - mongodb
    networks:
      - tts-flow-network
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mongodb_data:

networks:
  tts-flow-network:
    driver: bridge 